### ISSUE TITLE
Update to 0.12?

### ISSUE THREAD

**Issue by artokun** [kiwiyou/bevy-ws-server#4]
I tried forking and updating it to the latest bevy version but failed miserably.

**Comment by artokun** [comment]
kudos to @stumbinbear for helping me identify the issue here

>@stumblinbear: FakeTask is shadowing improperly with the single threaded executor

ref:
https://github.com/bevyengine/bevy/issues/10579

**Comment by kiwiyou** [comment]
Merged #5.
